### ISSUE TITLE
nameserver added to the end of /etc/resolv.conf in Linux

### ISSUE THREAD

**Issue by ohthehugemanatee** [iamdork/compose#20]
Right now on my system, dork adds 127.0.0.1 to the end of my /etc/resolv.conf . That's a problem, because nslookup only tries subsequent servers only when the first server is not reachable. (see the [resolver](https://linux.die.net/man/5/resolver) and [resolv.conf](https://linux.die.net/man/5/resolv.conf) manpages). 

The local nameserver should be added to the TOP of the file.

**Comment by pmelab** [comment]
Fixed by f89543a93ccca9e31f93c1bb93ab161a9b33020b.
